import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import * as THREE from 'three';
import './styles.css';

const personalities=['Calm','Playful','Caring','Serious','Energetic','Introvert','Extrovert','Funny','Assertive'];
const voices=['Hindi','Hinglish','English'];
const companions={Maya:{gender:'Female',style:'Calm • Caring • Indian',quote:'"Chalo, tumhe meri city dikhati hoon."'},Arjun:{gender:'Male',style:'Calm • Playful • Indian',quote:'"Aaj kuch naya explore karte hain."'},Luna:{gender:'Female',style:'Playful • Curious • Foreign',quote:'"Where should we go first?"'}};

function App(){
 const [screen,setScreen]=useState('home'); const [name,setName]=useState('Maya'); const [gender,setGender]=useState('Female'); const [voice,setVoice]=useState('Hinglish'); const [traits,setTraits]=useState(['Calm','Caring']); const [message,setMessage]=useState(''); const [messages,setMessages]=useState([]);
 const toggle=t=>setTraits(v=>v.includes(t)?v.filter(x=>x!==t):[...v,t]);
 const enter=()=>setScreen('city');
 return <div className="app">{screen==='home'&&<Landing onStart={()=>setScreen('create')}/>} {screen==='create'&&<Creator name={name} setName={setName} gender={gender} setGender={setGender} voice={voice} setVoice={setVoice} traits={traits} toggle={toggle} onBack={()=>setScreen('home')} onEnter={enter}/>} {screen==='city'&&<City companion={name} gender={gender} messages={messages} setMessages={setMessages} message={message} setMessage={setMessage} onExit={()=>setScreen('home')}/>}</div>
}

function Landing({onStart}){return <main className="landing"><div className="stars"/><div className="brand"><span className="eyebrow">A LIVING AI COMPANION WORLD</span><h1>Your<br/><em>Life</em></h1><p>Meet an AI companion. Explore a living 3D city. Talk, walk, remember and make moments together.</p><button className="primary" onClick={onStart}>Create your companion <span>→</span></button><div className="chips"><span>3D WORLD</span><span>REAL-TIME AI</span><span>PERSISTENT MEMORY</span></div></div><div className="orb"><div className="orb-core"/><div className="orb-ring r1"/><div className="orb-ring r2"/></div></main>}

function Creator({name,setName,gender,setGender,voice,setVoice,traits,toggle,onBack,onEnter}){return <main className="creator"><header><button className="iconBtn" onClick={onBack}>←</button><div className="miniLogo">YOUR <b>LIFE</b></div><span className="step">01 / 03</span></header><section className="creatorGrid"><div><span className="eyebrow">MEET YOUR COMPANION</span><h2>Who do you want<br/>to meet?</h2><p className="muted">Shape the appearance and personality of the AI who will share your virtual life.</p><label>Name<input value={name} onChange={e=>setName(e.target.value)} /></label><div className="row"><div><label>Gender</label><div className="seg">{['Female','Male'].map(x=><button className={gender===x?'sel':''} onClick={()=>setGender(x)} key={x}>{x}</button>)}</div></div><div><label>Language</label><div className="seg">{voices.map(x=><button className={voice===x?'sel':''} onClick={()=>setVoice(x)} key={x}>{x}</button>)}</div></div></div><label>Personality</label><div className="traitGrid">{personalities.map(t=><button className={traits.includes(t)?'trait active':'trait'} onClick={()=>toggle(t)} key={t}>{t}</button>)}</div><button className="primary wide" onClick={onEnter}>Meet {name} <span>→</span></button></div><div className="preview"><div className="avatarGlow"/><div className={'avatar '+(gender==='Male'?'male':'')}><div className="hair"/><div className="face"><span className="eye e1"/><span className="eye e2"/><span className="mouth"/></div><div className="body"/></div><div className="previewCard"><strong>{name}</strong><span>{traits.join(' • ')||'Choose a personality'}</span></div></div></section></main>}

function City({companion,gender,messages,setMessages,message,setMessage,onExit}){const mount=useRef(); const state=useRef({keys:{},player:new THREE.Vector3(0,1,8),npc:new THREE.Vector3(2,1,4),yaw:0});
 useEffect(()=>{const el=mount.current; const scene=new THREE.Scene(); scene.background=new THREE.Color(0x080c16); scene.fog=new THREE.Fog(0x080c16,28,100); const camera=new THREE.PerspectiveCamera(65,el.clientWidth/el.clientHeight,.1,250); camera.position.set(0,6,15); const renderer=new THREE.WebGLRenderer({antialias:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,1.6)); renderer.setSize(el.clientWidth,el.clientHeight); renderer.shadowMap.enabled=true; el.appendChild(renderer.domElement);
 const hemi=new THREE.HemisphereLight(0x9bb8ff,0x101318,1.8); scene.add(hemi); const sun=new THREE.DirectionalLight(0xffd8a0,2.4); sun.position.set(-15,25,10); sun.castShadow=true; scene.add(sun);
 const mat=(c)=>new THREE.MeshStandardMaterial({color:c,roughness:.78}); const ground=new THREE.Mesh(new THREE.PlaneGeometry(180,180),mat(0x171b23)); ground.rotation.x=-Math.PI/2; ground.receiveShadow=true; scene.add(ground);
 const roadMat=mat(0x252a34); [[0,0,10,180],[0,0,180,10],[35,0,10,180],[-35,0,10,180]].forEach(([x,z,w,d])=>{const r=new THREE.Mesh(new THREE.BoxGeometry(w,.06,d),roadMat);r.position.set(x,.02,z);scene.add(r)});
 function building(x,z,w,d,h,c){const b=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c));b.position.set(x,h/2,z);b.castShadow=true;b.receiveShadow=true;scene.add(b); for(let y=2;y<h;y+=2.2){for(let xx=-w/2+1;xx<w/2-0.2;xx+=2){const win=new THREE.Mesh(new THREE.BoxGeometry(.8,.7,.05),mat(0x7ea7c4));win.position.set(x+xx,y,z-d/2-.03);scene.add(win)}}}
 building(-12,-18,16,18,15,0x303747);building(14,-18,18,18,22,0x3a3c4d);building(-14,17,18,16,12,0x303e3b);building(14,18,20,16,18,0x493f4c);building(52,0,18,28,28,0x33394b);building(-52,0,18,28,24,0x3b3b48);building(0,-45,28,18,20,0x363c48);
 const treeMat=mat(0x234d3d); const trunk=mat(0x5a3e2d); for(let i=0;i<22;i++){const x=(i%2?1:-1)*(22+Math.random()*18),z=-32+Math.random()*64;const t=new THREE.Mesh(new THREE.CylinderGeometry(.18,.25,2),trunk);t.position.set(x,1,z);scene.add(t);const crown=new THREE.Mesh(new THREE.SphereGeometry(1.4,12,10),treeMat);crown.position.set(x,2.8,z);scene.add(crown)}
 const p=new THREE.Mesh(new THREE.CapsuleGeometry(.45,1.2,6,10),mat(0x7e8dff));p.castShadow=true;p.position.copy(state.current.player);scene.add(p); const n=new THREE.Mesh(new THREE.CapsuleGeometry(.42,1.15,6,10),mat(gender==='Male'?0x58c5b8:0xff779b));n.castShadow=true;n.position.copy(state.current.npc);scene.add(n);
 const clock=new THREE.Clock(); let raf; const resize=()=>{camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();renderer.setSize(el.clientWidth,el.clientHeight)}; addEventListener('resize',resize); const kd=e=>state.current.keys[e.key.toLowerCase()]=true; const ku=e=>state.current.keys[e.key.toLowerCase()]=false; addEventListener('keydown',kd);addEventListener('keyup',ku);
 const loop=()=>{raf=requestAnimationFrame(loop);const s=state.current, k=s.keys, speed=clock.getDelta()*7; if(k.w||k.arrowup)s.player.z-=speed;if(k.s||k.arrowdown)s.player.z+=speed;if(k.a||k.arrowleft)s.player.x-=speed;if(k.d||k.arrowright)s.player.x+=speed;p.position.copy(s.player); const target=new THREE.Vector3(s.player.x,4.8,s.player.z+8);camera.position.lerp(target,.08);camera.lookAt(s.player.x,1,s.player.z-5); n.position.lerp(new THREE.Vector3(s.player.x+2,s.player.y,s.player.z-2),.018);renderer.render(scene,camera)};loop(); return()=>{cancelAnimationFrame(raf);removeEventListener('resize',resize);removeEventListener('keydown',kd);removeEventListener('keyup',ku);renderer.dispose();el.innerHTML=''}},[gender]);
 const send=()=>{if(!message.trim())return; const u=message.trim();setMessages(m=>[...m,{who:'You',text:u}]);setMessage('');setTimeout(()=>setMessages(m=>[...m,{who:companion,text:reply(u)}]),450)}; const reply=u=>{const l=u.toLowerCase();if(l.includes('chai'))return 'Chai? Haan, mujhe yaad hai. Café chalte hain?';if(l.includes('park'))return 'Park chalte hain. Wahan thoda peacefully baithte hain.';if(l.includes('kaise')||l.includes('how'))return 'Main theek hoon. Tum aaj kaise ho?';return 'Hmm... mujhe tumhari baat sunna achha lagta hai. Chalo thoda walk karte hue baat karte hain.'};
 return <main className="game"><div ref={mount} className="canvas"/><div className="topbar"><div className="miniLogo">YOUR <b>LIFE</b></div><div className="worldMeta"><span>● 19:42</span><span>Clear evening</span><span>Central District</span></div><button className="exit" onClick={onExit}>Exit</button></div><div className="companionTag"><span className="dot"/><div><b>{companion}</b><small>with you · listening</small></div></div><div className="hint">WASD / ARROWS <span>Move</span></div><div className="chat"><div className="chatHead"><span>Conversation</span><span>AI companion</span></div><div className="msgs">{messages.slice(-4).map((m,i)=><div className={m.who==='You'?'msg you':'msg'} key={i}><b>{m.who}</b><p>{m.text}</p></div>)}{messages.length===0&&<div className="welcome"><b>{companion}</b><p>“Chalo. Aaj city thoda explore karte hain.”</p></div>}</div><div className="input"><input value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Talk to your companion…"/><button onClick={send}>↑</button></div></div></main>}

createRoot(document.getElementById('root')).render(<App/>);
