import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
import RealisticCity from './RealisticCity.jsx';

const traits=['Calm','Energetic','Serious','Playful','Reserved','Social','Caring','Independent','Introverted','Extroverted','Funny','Serious','Curious','Straightforward','Assertive','Gentle'];
const screens=['splash','language','login','type','appearance','outfit','personality','culture','review','intro','hud','voice','text','activities','map','cafe','actions','phone','inventory','memories','relationship','settings','save'];
const activities=[['Walk Together','🚶'],['Have a Meal','🍽'],['Go Shopping','🛍'],['Visit Park','🌳'],['Watch Movie','🎬'],['Travel','🚗'],['Take Photos','📷'],['Play Games','🎮'],['Park / Study','📚'],['Work Together','💻']];

function App(){
 const [screen,setScreen]=useState('splash'); const [language,setLanguage]=useState('Hinglish'); const [gender,setGender]=useState('Female'); const [name,setName]=useState('Shreya'); const [traitsSel,setTraitsSel]=useState(['Calm','Caring','Playful']); const [culture,setCulture]=useState('Indian'); const [voice,setVoice]=useState('Aanya'); const [message,setMessage]=useState(''); const [messages,setMessages]=useState([]); const [activeTab,setActiveTab]=useState('All'); const [activity,setActivity]=useState(null); const [memory,setMemory]=useState(['First Meeting','Coffee at Riverside Café','Walk in Central Park','Watched a Movie']);
 const toggle=t=>setTraitsSel(v=>v.includes(t)?v.filter(x=>x!==t):[...v,t]);
 const next=s=>setScreen(s); const send=()=>{if(!message.trim())return;const u=message.trim();setMessages(v=>[...v,{me:true,t:u}]);setMessage('');setTimeout(()=>setMessages(v=>[...v,{me:false,t:reply(u)}]),350)};
 const reply=u=>{const l=u.toLowerCase(); if(l.includes('chai')){setMemory(v=>v.includes('Likes Chai')?v:['Likes Chai',...v]);return 'Haan, chai yaad hai. Riverside Café chalte hain?';} if(l.includes('park'))return 'Chalo park chalte hain. Aaj weather bhi nice hai.'; if(l.includes('sad')||l.includes('upset'))return 'Tum thode quiet lag rahe ho. Baat karna chaho to main sun rahi hoon.'; return 'Hmm, samajh rahi hoon. Chalo thoda walk karte hue baat karte hain.'};
 return <div className="app">
  {screen==='splash'&&<Splash onNext={()=>next('language')}/>} {screen==='language'&&<Language language={language} setLanguage={setLanguage} onNext={()=>next('login')} />}
  {screen==='login'&&<Login onNext={()=>next('type')}/>} {screen==='type'&&<Type gender={gender} setGender={setGender} onNext={()=>next('appearance')} />}
  {screen==='appearance'&&<Appearance gender={gender} onNext={()=>next('outfit')} />} {screen==='outfit'&&<Outfit onNext={()=>next('personality')}/>} 
  {screen==='personality'&&<Personality selected={traitsSel} toggle={toggle} onNext={()=>next('culture')}/>} {screen==='culture'&&<Culture culture={culture} setCulture={setCulture} language={language} setLanguage={setLanguage} voice={voice} setVoice={setVoice} onNext={()=>next('review')}/>} 
  {screen==='review'&&<Review name={name} setName={setName} gender={gender} traits={traitsSel} culture={culture} language={language} onNext={()=>next('intro')}/>} {screen==='intro'&&<Intro name={name} onNext={()=>next('hud')}/>} 
  {screen==='hud'&&<Game name={name} gender={gender} onOpen={next} onExit={()=>next('save')}/>} {screen==='voice'&&<Conversation name={name} voiceMode messages={messages} message={message} setMessage={setMessage} send={send} onBack={()=>next('hud')} onOpen={next}/>} 
  {screen==='text'&&<Conversation name={name} messages={messages} message={message} setMessage={setMessage} send={send} onBack={()=>next('hud')} onOpen={next}/>} {screen==='activities'&&<Activities activity={activity} setActivity={setActivity} onBack={()=>next('hud')} onOpen={next}/>} 
  {screen==='map'&&<Map onBack={()=>next('hud')} onGo={()=>next('cafe')}/>} {screen==='cafe'&&<Cafe name={name} onBack={()=>next('map')} onOpen={next}/>} {screen==='actions'&&<Actions onBack={()=>next('hud')}/>} 
  {screen==='phone'&&<Phone onBack={()=>next('hud')} onOpen={next}/>} {screen==='inventory'&&<Inventory onBack={()=>next('phone')}/>} {screen==='memories'&&<Memories memory={memory} onBack={()=>next('voice')}/>} {screen==='relationship'&&<Relationship name={name} onBack={()=>next('voice')}/>} 
  {screen==='settings'&&<Settings onBack={()=>next('phone')}/>} {screen==='save'&&<Save onSave={()=>next('splash')} onCancel={()=>next('hud')}/>} 
 </div>
}

const Shell=({children,onBack,step,title})=><main className="screen"><header className="screenHead"><button className="roundBtn" onClick={onBack}>‹</button><div className="brandMini">YOUR <b>LIFE</b></div>{step&&<span className="step">{step}</span>}</header>{title&&<div className="screenTitle"><h2>{title}</h2></div>}{children}</main>;
const Button=({children,onClick,secondary=false})=><button className={secondary?'btn secondary':'btn'} onClick={onClick}>{children}</button>;
function Splash({onNext}){useEffect(()=>{const t=setTimeout(onNext,1600);return()=>clearTimeout(t)},[]);return <main className="splash"><div className="cityBackdrop"/><div className="splashShade"/><div className="splashContent"><div className="brandHuge">YOUR <span>LIFE</span></div><p>A 3D AI COMPANION LIFE SIMULATION</p><div className="loader"><i/><b>72%</b></div><small>VASUKI STUDIOS</small></div></main>}
function Language({language,setLanguage,onNext}){return <Shell step="02 / 23" title="Choose Language" onBack={()=>setLanguage(language)}><div className="panel narrow"><div className="globe">◎</div><p className="muted center">You can change this later in settings.</p>{['🇮🇳  हिंदी (Hindi)','🇮🇳  Hinglish (Hindi + English)','🇺🇸  English','◎  Other Languages'].map((x,i)=><button key={x} className={'option '+((i===1&&language==='Hinglish')||(i===0&&language==='Hindi')||(i===2&&language==='English')?'chosen':'')} onClick={()=>setLanguage(i===0?'Hindi':i===2?'English':'Hinglish')}>{x}</button>)}<Button onClick={onNext}>Continue</Button></div></Shell>}
function Login({onNext}){return <Shell step="03 / 23" title="Welcome Back" onBack={()=>onNext()}><div className="auth panel"><p className="muted center">Continue your journey</p><input placeholder="✉  Email / Phone Number"/><input placeholder="▣  Password" type="password"/><label className="check"><input type="checkbox" defaultChecked/> Remember me <span>Forgot Password?</span></label><Button onClick={onNext}>Sign In</Button><div className="or">or continue with</div><div className="social"><button>G Google</button><button>● Apple</button></div><button className="guest" onClick={onNext}>◉ Guest Mode</button><p className="tiny center">Don't have an account? <b>Create Account</b></p></div></Shell>}
function Type({gender,setGender,onNext}){return <Shell step="04 / 23" title="Choose Your Companion" onBack={()=>setGender(gender)}><div className="typeGrid">{['Male','Female'].map(g=><button className={'typeCard '+(gender===g?'selected':'')} key={g} onClick={()=>setGender(g)}><div className={'portrait '+g.toLowerCase()}/><strong>{g}</strong></button>)}</div><div className="bottomAction"><Button onClick={onNext}>Next</Button></div></Shell>}
function Appearance({gender,onNext}){return <Shell step="05 / 23" title="Appearance Customization" onBack={()=>onNext()}><div className="customLayout"><div className="sideMenu">{['▣ Presets','◉ Face','◌ Hair','♟ Body','◈ Outfit','◇ Accessories'].map((x,i)=><button className={i===1?'active':''} key={x}>{x}</button>)}</div><div className="largePortrait"><div className={'portraitBig '+gender.toLowerCase()}/><div className="faceDots">{[1,2,3,4,5].map(i=><span key={i}/>)}</div></div></div><div className="bottomAction"><Button onClick={onNext}>Next</Button></div></Shell>}
function Outfit({onNext}){return <Shell step="06 / 23" title="Outfit & Accessories" onBack={()=>onNext()}><div className="tabs"><button className="active">Outfits</button><button>Accessories</button></div><div className="outfitLayout"><div className="fullFigure"><div className="portraitBig female"/><div className="outfitBody">♡</div></div><div className="outfitChoices">{['pink','denim','red','hoodie'].map(c=><button key={c}><span className={'outfitThumb '+c}/></button>)}</div></div><div className="bottomAction"><Button onClick={onNext}>Next</Button></div></Shell>}
function Personality({selected,toggle,onNext}){const pairs=[['Calm','Energetic'],['Serious','Playful'],['Reserved','Social'],['Caring','Independent'],['Introverted','Extroverted'],['Funny','Serious'],['Curious','Straightforward'],['Assertive','Gentle']];return <Shell step="07 / 23" title="Set Their Personality" onBack={()=>onNext()}><p className="muted center">Combine multiple traits.</p><div className="sliders">{pairs.map(([a,b])=><div className="sliderRow" key={a}><span>{a}</span><input type="range" defaultValue={selected.includes(a)?25:50}/><span>{b}</span></div>)}</div><div className="traitGrid">{traits.map(t=><button key={t} className={selected.includes(t)?'pill chosen':'pill'} onClick={()=>toggle(t)}>{t}</button>)}</div><div className="bottomAction"><Button onClick={onNext}>Next</Button></div></Shell>}
function Culture({culture,setCulture,language,setLanguage,voice,setVoice,onNext}){return <Shell step="08 / 23" title="Culture & Communication" onBack={()=>onNext()}><div className="formPanel"><p className="muted">This shapes how they talk and behave.</p><label>Cultural Background<select value={culture} onChange={e=>setCulture(e.target.value)}><option>Indian</option><option>Foreigner</option><option>Mixed</option></select></label><label>Primary Language<select value={language} onChange={e=>setLanguage(e.target.value)}><option>Hinglish (Hindi + English)</option><option>Hindi</option><option>English</option></select></label><label>Tone<select><option>Casual & Friendly</option><option>Warm & Calm</option><option>Playful</option></select></label><label>Voice<div className="voiceChoice"><span>👩 {voice} (Natural)</span><button onClick={()=>setVoice(voice==='Aanya'?'Riya':'Aanya')}>▶</button></div></label></div><div className="bottomAction"><Button onClick={onNext}>Create Companion</Button></div></Shell>}
function Review({name,setName,gender,traits,culture,language,onNext}){return <Shell step="09 / 23" title="Review Your Companion" onBack={()=>onNext()}><div className="reviewCard"><div className="reviewPortrait"><div className={'portraitBig '+gender.toLowerCase()}/></div><div className="reviewInfo"><label>Name<input value={name} onChange={e=>setName(e.target.value)}/></label>{[['Appearance','Custom'],['Personality',traits.slice(0,2).join(', ')],['Culture',culture],['Language',language],['Voice','Natural']].map(x=><div className="kv" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}<Button secondary onClick={()=>{}}>Edit</Button></div></div><div className="bottomAction"><Button onClick={onNext}>Confirm & Start</Button></div></Shell>}
function Intro({name,onNext}){return <main className="intro"><div className="introScene"/><div className="introBubble"><span>Hey! 👋</span><b>Nice to finally meet you!</b></div><div className="introPerson"><div className="portraitBig female"/></div><div className="introBottom"><p>This is the beginning of something special.</p><Button onClick={onNext}>Continue</Button></div></main>}
function Game({name,gender,onOpen,onExit}){return <RealisticCity name={name} gender={gender} onOpen={onOpen} onExit={onExit}/>}
function Conversation({name,voiceMode,messages,message,setMessage,send,onBack,onOpen}){return <Shell title={voiceMode?'Conversation (Voice Mode)':'Conversation (Text Mode)'} onBack={onBack}><div className="conversation"><div className="conversationHead"><div className="miniAvatar female"/><div><b>{name}</b><small>Happy · Close</small></div><div className="headActions"><button onClick={()=>onOpen('memories')}>Memory</button><button>Topics</button><button onClick={()=>onOpen('activities')}>Activities</button></div></div><div className="chatArea">{messages.length?messages.map((m,i)=><div className={m.me?'bubble me':'bubble'} key={i}>{m.t}</div>):<><div className="bubble">Hey! How was your day?</div><div className="bubble me">It was good! Went to a café.</div><div className="bubble">That sounds nice. Next time, let's go together.</div></>}</div>{voiceMode&&<div className="wave"><i/><i/><i/><i/><i/><i/><i/><i/><i/><button onClick={send}>●</button></div>}<div className="chatInput"><input value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder={voiceMode?'Or type a message...':'Type a message...'}/><button onClick={send}>➤</button></div></div></Shell>}
function Activities({onBack,activity,setActivity,onOpen}){return <Shell title="Choose an Activity" onBack={onBack}><div className="activityGrid">{activities.map(([a,icon])=><button className={activity===a?'activity selected':'activity'} onClick={()=>{setActivity(a);if(a==='Walk Together')onOpen('hud')}} key={a}><span>{icon}</span><b>{a}</b></button>)}<button className="activity more" onClick={()=>onOpen('map')}>⌘<b>More Activities</b></button></div></Shell>}
function Map({onBack,onGo}){return <Shell title="City Map" onBack={onBack}><div className="mapTabs"><button className="active">All</button><button>Cafés</button><button>Shops</button><button>Parks</button><button>Homes</button><button>Activities</button></div><div className="mapCanvas"><div className="mapRoad r1"/><div className="mapRoad r2"/><div className="mapRoad r3"/><span className="pin home">⌂<small>Apartment</small></span><span className="pin park">●<small>Park</small></span><span className="pin cafe">●<small>Café</small></span><span className="pin shop">▣<small>Shop</small></span><span className="pin rest">♟<small>Restaurant</small></span><span className="pin gym">◆<small>Gym</small></span><span className="youPin">➤</span></div><div className="mapFooter"><b>Riverside Café</b><span>A cozy place to talk and relax.</span><Button onClick={onGo}>Go Here</Button></div></Shell>}
function Cafe({name,onBack,onOpen}){return <Shell title="Riverside Café" onBack={onBack}><div className="cafeScene"><div className="cafeTable"/><div className="cafePerson"><div className="portraitBig female"/></div><div className="cafeActions"><button onClick={()=>onOpen('voice')}>▣ Talk</button><button>☕ Have Coffee</button><button>📷 Take Photo</button><button onClick={onBack}>← Leave</button></div></div><div className="locationCaption"><b>{name}</b> is waiting with you. <span>Downtown · Evening</span></div></Shell>}
function Actions({onBack}){return <Shell title="Companion Actions" onBack={onBack}><div className="actionGrid">{['Walking','Sitting','Talking','Using Phone','Taking Photo','Entering Building'].map(x=><button key={x}><div className="actionVisual">◉</div><b>{x}</b></button>)}</div></Shell>}
function Phone({onBack,onOpen}){return <Shell title="Phone / In-Game Apps" onBack={onBack}><div className="phoneDate">Tue, 12 Mar <span>☀ 24°C Clear</span></div><div className="appGrid">{[['Map','📍','map'],['Companion','💗','voice'],['Messages','✉','text'],['Tasks','✓','activities'],['Inventory','▣','inventory'],['Camera','📷','voice'],['Gallery','▧','memories'],['Settings','⚙','settings'],['Exit Game','⏻','save']].map(([x,i,s])=><button key={x} onClick={()=>onOpen(s)}><span>{i}</span><b>{x}</b></button>)}</div></Shell>}
function Inventory({onBack}){return <Shell title="Inventory" onBack={onBack}><div className="inventoryTabs"><button className="active">All</button><button>Gifts</button><button>Food</button><button>Clothing</button><button>Misc</button></div><div className="items">{['☕ Coffee','🌹 Rose','🧸 Teddy Bear','🎁 Gift Box','📱 Phone','📷 Camera','⌚ Watch','📕 Book','🍕 Chocolates','◉ Collectible','＋ Rare Objects'].map(x=><button key={x}>{x}</button>)}</div></Shell>}
function Memories({memory,onBack}){return <Shell title="Our Memories" onBack={onBack}><div className="memoryTabs"><button className="active">All</button><button>Conversations</button><button>Places</button><button>Activities</button><button>Photos</button></div><div className="memoryList">{memory.map((m,i)=><div className="memory" key={m}><div className="memoryThumb">{['👋','☕','🌳','🎬','❤️'][i%5]}</div><div><b>{m}</b><small>{i===0?'First Meeting':i===1?'Today · Talked about memories':i===2?'Today · Enjoyed the sunset':'Yesterday · A great time together.'}</small></div><span>♡</span></div>)}</div></Shell>}
function Relationship({name,onBack}){return <Shell title="Relationship Status" onBack={onBack}><div className="relationship"><div className="relationshipHero"><div className="portraitBig female"/><div><h2>{name}</h2><b>Happy · Close</b></div><strong>♥</strong></div><div className="stats"><div><span>●</span><b>Mood</b><small>Happy</small></div><div><span>♥</span><b>Relationship</b><small>Close</small></div><div><span>⚡</span><b>Energy</b><small>75%</small></div></div><div className="progress"><i/></div><p>You've spent <b>12 hours</b> together.<br/>Here's to many more memories!</p><Button onClick={()=>{}}>View Details</Button></div></Shell>}
function Settings({onBack}){return <Shell title="Settings" onBack={onBack}><div className="settingsList">{[['◉','Graphics','High'],['◉','Audio',''],['◉','Voice & Language','Hinglish'],['◉','Controls',''],['◉','Gameplay',''],['◉','Privacy & Data',''],['◉','Help & Support',''],['◉','About','VASUKI STUDIOS']].map(x=><button key={x[1]}><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]}</small><i>›</i></button>)}</div></Shell>}
function Save({onSave,onCancel}){return <main className="save"><div className="saveCity"/><div className="saveCard"><h2>Save Your Progress?</h2><p>Your companion, memories and world state<br/>will be saved.</p><Button onClick={onSave}>Save & Exit</Button><Button secondary onClick={onCancel}>Cancel</Button></div></main>}
createRoot(document.getElementById('root')).render(<App/>);
